# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the review was submitted')),
                ('review_rating', models.FloatField(blank=True, help_text='Overall rating (1.0 to 10.0), set by service layer if not provided', null=True)),
                ('cleanliness_rating', models.FloatField(blank=True, help_text='Cleanliness rating (1.0 to 10.0)', null=True)),
                ('location_rating', models.FloatField(blank=True, help_text='Location rating (1.0 to 10.0)', null=True)),
                ('comfort_rating', models.FloatField(blank=True, help_text='Comfort rating (1.0 to 10.0)', null=True)),
                ('facilities_rating', models.FloatField(blank=True, help_text='Facilities rating (1.0 to 10.0)', null=True)),
                ('staff_rating', models.FloatField(blank=True, help_text='Staff rating (1.0 to 10.0)', null=True)),
                ('value_for_money_rating', models.FloatField(blank=True, help_text='Value for money rating (1.0 to 10.0)', null=True)),
                ('comment', models.TextField(blank=True, help_text="Guest's written review", null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the review has been approved by the host or admin')),
                ('host_response', models.TextField(blank=True, help_text="Host's response to the review", null=True)),
                ('response_date', models.DateTimeField(blank=True, help_text='Date the host responded', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether the review is publicly visible')),
                ('booking', models.OneToOneField(help_text='The booking associated with this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
