# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(help_text='The listing being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The guest who wrote the review', limit_choices_to={'user_role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='guest_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking', 'review_date'], name='reviews_rev_booking_06e20d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'is_approved'], name='reviews_rev_user_id_a31224_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['listing', 'is_public'], name='reviews_rev_listing_069964_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_rating__gte', 1.0), ('review_rating__lte', 10.0)), ('review_rating__isnull', True), _connector='OR'), name='valid_review_rating_range'),
        ),
    ]
