# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the conversation was started')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last message or update')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the conversation is active or archived')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_content', models.TextField(help_text='The content of the message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the message was sent')),
                ('read', models.BooleanField(default=False, help_text='Whether the message has been read by the receiver')),
                ('edited', models.BooleanField(default=False, help_text='Whether the message has been edited')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
