# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guest',
            field=models.ForeignKey(help_text='The guest participating in the conversation', limit_choices_to={'user_role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='guest_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='host',
            field=models.ForeignKey(help_text='The host participating in the conversation', limit_choices_to={'user_role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='host_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(help_text='The listing related to this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(help_text='The user intended to receive the message', limit_choices_to={'user_role__in': ['guest', 'host']}, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='The user who sent the message', limit_choices_to={'user_role__in': ['guest', 'host']}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['listing', 'created_at'], name='messaging_c_listing_96e465_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['guest', 'host'], name='messaging_c_guest_i_d8dc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active'], name='messaging_c_is_acti_3f43be_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('guest', 'host', 'listing'), name='unique_conversation_per_guest_host_listing'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='messaging_m_convers_91f1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'read'], name='messaging_m_sender__12c98b_idx'),
        ),
    ]
