# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid (including taxes and fees)', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax component of the payment (set by service layer)', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Service fee component of the payment (set by service layer)', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the payment was processed')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('CHAPA', 'Chapa'), ('PAYPAL', 'PayPal'), ('MOBILE_MONEY', 'Mobile Money'), ('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer')], help_text='Method used for the payment', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('FULLY_REFUNDED', 'Fully Refunded'), ('PROCESSING', 'Processing')], default='PENDING', help_text='Current status of the payment', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique identifier from the payment gateway', max_length=100, null=True, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded, if any (set by service layer)', max_digits=10)),
                ('refund_date', models.DateTimeField(blank=True, help_text='Date and time the refund was processed', null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency of the payment (e.g., USD, EUR)', max_length=3)),
                ('booking', models.ForeignKey(help_text='The booking associated with this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
