# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geospatial coordinates (longitude, latitude)', srid=4326)),
                ('address', models.CharField(help_text='Street address of the property', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('distance_from_center', models.FloatField(blank=True, help_text='Distance from city center in kilometers', null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Maximum number of guests')),
                ('bedrooms', models.PositiveIntegerField(default=1, help_text='Number of bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='Number of bathrooms')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel'), ('guest_house', 'Guest House'), ('homestay', 'Homestay'), ('villa', 'Villa'), ('holiday_home', 'Holiday Home'), ('hostel', 'Hostel'), ('capsule_hotel', 'Capsule Hotel'), ('resort', 'Resort'), ('holiday_park', 'Holiday Park'), ('boat', 'Boat'), ('lodge', 'Lodge'), ('love_hotel', 'Love Hotel')], default='apartment', max_length=50)),
                ('average_review_score', models.FloatField(blank=True, help_text='Average review score (1-10)', null=True)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Number of approved reviews')),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('sustainability_certified', models.BooleanField(default=False, help_text='Property has sustainability certification')),
                ('is_beachfront', models.BooleanField(default=False, help_text='Property is beachfront')),
                ('is_entire_place', models.BooleanField(default=False, help_text='Entire home/apartment')),
                ('pets_allowed', models.BooleanField(default=False, help_text='Pets are allowed')),
                ('adults_only', models.BooleanField(default=False, help_text='Adults-only property')),
                ('check_in_time', models.TimeField(blank=True, help_text='Check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Check-out time', null=True)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict'), ('non_refundable', 'Non-Refundable')], default='flexible', max_length=20)),
                ('house_rules', models.TextField(blank=True, help_text='House rules (e.g., no smoking, no parties)', null=True)),
                ('child_policy', models.TextField(blank=True, help_text='Child policy (e.g., age restrictions, extra charges)', null=True)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text="Detailed amenities (e.g., {'wifi': true, 'pool': false, 'air_conditioning': true})")),
                ('room_facilities', models.JSONField(blank=True, default=dict, help_text="Room-specific facilities (e.g., {'sea_view': true, 'private_bathroom': false})")),
                ('accessibility_features', models.JSONField(blank=True, default=dict, help_text="Accessibility features (e.g., {'wheelchair_accessible': true, 'toilet_with_grab_rails': false})")),
                ('activities', models.JSONField(blank=True, default=dict, help_text="Activities available (e.g., {'diving': true, 'golf_course': false})")),
                ('landmarks', models.JSONField(blank=True, default=dict, help_text="Nearby landmarks with distances (e.g., {'Haller Park': 1.3, 'Fort Jesus': 0.7})")),
                ('availability', models.JSONField(blank=True, default=dict, help_text="Availability calendar (e.g., {'2025-06-01': true})")),
                ('check_in_instructions', models.TextField(blank=True, help_text='Instructions for check-in (e.g., access code)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='property_images/default.jpg', help_text='Image file of the property', upload_to='property_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility and SEO', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
