# Generated by Django 5.2.4 on 2025-07-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(limit_choices_to={'user_role': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='property_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='listing',
            field=models.ForeignKey(help_text='The listing this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['host', 'city', 'country'], name='listings_li_host_id_b5faa6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_type'], name='listings_li_propert_7a505c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['average_review_score'], name='listings_li_average_01a1da_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['star_rating'], name='listings_li_star_ra_1baf21_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location'], name='listings_li_locatio_4bc07d_idx'),
        ),
    ]
