# Generated by Django 5.2.4 on 2025-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, help_text='Street address of the property', max_length=200, null=True),
        ),
    ]
