# Generated by Django 5.2.4 on 2025-07-15 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guests', models.PositiveIntegerField(default=1, help_text='Number of guests (must not exceed listing capacity)')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('FULLY_REFUNDED', 'Fully Refunded')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount including taxes and fees (set by service layer)', max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount applied to the booking (set by service layer)', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Service fee charged by the platform (set by service layer)', max_digits=10)),
                ('cancellation_deadline', models.DateTimeField(blank=True, help_text='Deadline for free cancellation (set by service layer)', null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Guest special requests (e.g., early check-in)', null=True)),
                ('is_instant_book', models.BooleanField(default=False, help_text='Booking is instantly confirmed without host approval')),
                ('activation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('activation_code_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
